window.env = {
    FIREBASE_API_KEY: import.meta.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: import.meta.env.IREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: import.meta.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: import.meta.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: import.meta.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: import.meta.env.FIREBASE_APP_ID
};
